data:
  root: ./VSL-video

model:
  type: slowfast
  num_classes: 10
  pretrained: true
  num_frames: 32   
  img_size: 224
  alpha: 4      

training:
  model_dir: outputs_SlowFast
  optimization:
    optimizer: adamw
    learning_rate: 1e-4
    weight_decay: 0.01
    scheduler: cosine
    warmup_epochs: 5


max_acc: 88.0
